### ISSUE TITLE
Data downsampler

### ISSUE THREAD

**Issue by oplehto** [jumptrading/influx-spout#100]
One thing in the Influx stack that is not really solved is the lack of decent support for downsampling  data for long term storage.  

Currently the approaches are InfluxDB Continuous Queries or using Kapacitor. Both of these are not really ideal for situations where we need to deal with a huge amount of measurements and fields. (For more details, see: https://www.slideshare.net/influxdata/downsampling-data and https://github.com/influxdata/influxdb/issues/7198)

I'd be happy with getting a downsampled copy of to a set of dedicated archive InfluxDB instances. Just having a "mean over N seconds" for each series with a numerical value would be fine. 

Perhaps we could have such a downsampler in the writer or a separate agent that's sitting on the NATS bus republishing the normal data into downsampled streams.

**Comment by mjs** [comment]
Makes sense. Sounds fun :) Without thinking about it too hard, a new component which sits between the filter and the writer seems cleaner to me. I'm sure there's some tricky parts to this. I'll do some more thinking about it next week.

**Comment by mjs** [comment]
Consider whether downsampling will happen in the writer are as a separate component. Configuration-wise it would be simpler to have it in the writer.

**Comment by mjs** [comment]
Done in #105
