### ISSUE TITLE
Consider create a Dockerfile with compiler included

### ISSUE THREAD

**Issue by jmorcar** [jumptrading/influx-spout#142]
I propose a new Dockerfile. It compiles go project and create docker image, maybe using "git clone" to project instead of local folder would be better.
I had to remove "check-git" step on Makefile because this produce erros when execute "RUN make".

In detail, the line on Makefile:
all: deps check-git influx-spout influx-spout-tap
Is changed by:
all: deps influx-spout influx-spout-tap

Here my dockerfile:

<code>
------------------------------------------------------------------------------------

FROM golang:1.9.1-alpine AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=1

---### Add git make and bash
RUN apk add --no-cache git make bash

RUN mkdir $GOPATH/src/my-project

---### copy from local directory
COPY . $GOPATH/src/my-project

WORKDIR $GOPATH/src/my-project

---## #Build the application

RUN make && cp influx-spout /tmp/ && cp influx-spout-tap /tmp/ && cp example-udp-listener.conf /tmp/ && cp example-http-listener.conf /tmp/

FROM alpine:3.7
COPY --from=builder /tmp/influx-spout /bin/

COPY --from=builder /tmp/influx-spout-tap /bin/

COPY --from=builder /tmp/example-udp-listener.conf /etc/influx-spout/udp-listener.toml

COPY --from=builder /tmp/example-http-listener.conf /etc/influx-spout/http-listener.toml

RUN apk update && apk add dumb-init && rm -rf /var/cache/apk/*

---### Allow influx-spout to receive signals
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/bin/influx-spout"]
CMD ["/etc/influx-spout/http-listener.toml"]

----### END:

---------------------------------------------------------------------------------------
</code>

**Comment by mjs** [comment]
Hi, thanks for this.

What's the main reason for this Dockerfile? Building influx-spout without having to install the Go toolchain? Understanding the motivation would help with deciding how to proceed.

**Comment by jmorcar** [comment]
Exactly a Dockerfile that create a image directly where the  goland compiler is a step in the image creation only to running the docker container more fast. My test was ok with the example that I posted before, but surely you think of something better of my dockerfile example.

**Comment by jortkoopmans** [comment]
Hi, great idea @jmorcar .
Generally it is recommended to build binaries in docker, to ensure consistent environment and remove host level dependencies (e.g. anti-pattern 10 here; https://medium.com/containers-101/docker-anti-patterns-ad2a1fcd5ce1).
I think the recommended solution is to use the multistage builds, as already highlighted by @jmorcar .
It will also make it easier for people to adopt influx-spout.

**Comment by mjs** [comment]
Can this be close now that #144 has landed?
