### ISSUE TITLE
Problem to receive Telegraf metrics

### ISSUE THREAD

**Issue by jmorcar** [jumptrading/influx-spout#143]
I'm trying to receive Telegraf metrics. 

I have to created a test lab with a telegraf agent sends to influx-spout lintener on 10001 upd, with subject "cpu" but when I check with influx-spout-tap command to browser the subject "cpu" , nothing is displayed.

### Check failed (Telegraf ---> Influx-spout  udp:10001 mode listener --->conneted ok nats-server:4222)
/ # influx-spout-tap -h nats://nats-server:4222 -s cpu
2019/11/19 12:32:19 Connected to nats://nats-server:4222
2019/11/19 12:32:19 Subscribing to subject cpu
^C

My telegraf machine have the version Telegraf 1.10.0 (git: HEAD fe33ee89) and configuration outputs is:

    [[outputs.socket_writer]]
      ## URL to connect to
      address = "udp://influx-spout-service:10001"

      ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
      data_format = "influx"  

However if I use the outputs plugin nats on telegraf aget, then I receive the messages of metrics well , because outputs plugin has the subject param (I typed "telegraf" , then I check with influx-spout-tap -s "telegraf" and the messages are received Ok in Nats protocol with influxdb format.

### Check OK (directly Telegraf --> NATS)

The telegraf agent has as well another output with nats plugin, this is the config:

-----------------------------------------------------------------------------
[[outputs.nats]]
       ## URLs of NATS servers
       servers = ["nats://nats-server:4222"]
       ## Optional credentials
       # username = ""
       # password = ""
       ## NATS subject for producer messages
       subject = "telegraf"
       
       ## Use Transport Layer Security
       # secure = false
       
       ## Optional TLS Config
       # tls_ca = "/etc/telegraf/ca.pem"
       # tls_cert = "/etc/telegraf/cert.pem"
       # tls_key = "/etc/telegraf/key.pem"
       ## Use TLS but skip chain & host verification
       # insecure_skip_verify = false
       
       ## Data format to output.
       ## Each data format has its own unique set of configuration options, read
       ## more about them here:
       ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
       data_format = "influx"

----------------------------------------------

This is the test OK, I read the subject "telegraf" directly from a telegraf agent:
<code>
/ # influx-spout-tap -h nats://nats-server:4222 -s telegraf
2019/11/19 10:53:12 Connected to nats://nats-server:4222
2019/11/19 10:53:12 Subscribing to subject telegraf
net,interface=all ip_outnoroutes=0i,ip_inhdrerrors=0i,ip_inreceives=7637i,icmp_outtimestampreps=0i,tcp_rtoalgorithm=1i,tcp_incsumerrors=0i,icmp_indestunreachs=2i,tcp_retranssegs=12i,udp_noports=0i,ip_indelivers=7637i,icmp_outaddrmaskreps=0i,tcp_passiveopens=0i,udplite_outdatagrams=0i,icmp_outtimeexcds=0i,icmpmsg_outtype3=2i,tcp_maxconn=-1i,ip_forwdatagrams=0i,ip_outdiscards=0i,icmp_outerrors=0i,icmp_outdestunreachs=2i,udp_rcvbuferrors=0i,udplite_sndbuferrors=0i,ip_inunknownprotos=0i,icmp_outmsgs=2i,tcp_outrsts=0i,udplite_inerrors=0i,ip_defaultttl=64i,icmp_inechoreps=0i,icmp_outaddrmasks=0i,icmp_outechoreps=0i,udplite_rcvbuferrors=0i,ip_reasmfails=0i,icmp_inredirects=0i,icmp_intimeexcds=0i,icmp_outredirects=0i,tcp_rtomin=200i,udp_incsumerrors=0i,tcp_outsegs=5757i,udplite_indatagrams=0i,ip_fragcreates=0i,icmp_inechos=0i,tcp_rtomax=120000i,tcp_inerrs=0i,tcp_currestab=2i,tcp_estabresets=0i,icmp_intimestamps=0i,tcp_insegs=7588i,ip_forwarding=1i,ip_reasmreqds=0i,ip_fragoks=0i,icmp_insrcquenchs=0i,icmp_inerrors=2i,icmp_outparmprobs=0i,ip_fragfails=0i,udplite_incsumerrors=0i,ip_reasmoks=0i,icmp_outtimestamps=0i,icmp_inaddrmaskreps=0i,icmpmsg_intype3=2i,udp_sndbuferrors=0i,udp_outdatagrams=2940i,ip_indiscards=0i,icmp_intimestampreps=0i,tcp_attemptfails=0i,udp_inerrors=0i,icmp_inaddrmasks=0i,icmp_incsumerrors=0i,icmp_outsrcquenchs=0i,udp_ignoredmulti=0i,udp_indatagrams=47i,ip_reasmtimeout=0i,icmp_outechos=0i,icmp_inparmprobs=0i,icmp_inmsgs=2i,tcp_activeopens=12i,udplite_noports=0i,ip_inaddrerrors=0i,ip_outrequests=8103i,udplite_ignoredmulti=0i 1574160800000000000
</code>

### Check connections on NATS server with HTTP gets

telegraf-deployment-8699897cc6-ptrl5:/# curl http://nats-server-http:8222/connz?subs=1
{
  "server_id": "NDLNP5QVUXB3H6DDS6JYPG5HWROKLD4T2DOU5KJ2AZQ5LSGECJ6JRDOP",
  "now": "2019-11-19T11:47:50.4509279Z",
  "num_connections": 2,
  "total": 2,
  "offset": 0,
  "limit": 1024,
  "connections": [
    {
      "cid": 1,
      "ip": "10.1.0.186",
      "port": 40488,
      "start": "2019-11-19T09:44:00.7205997Z",
      "last_activity": "2019-11-19T11:47:50.2584707Z",
      "rtt": "811µs",
      "uptime": "2h3m49s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 2477,
      "out_msgs": 0,
      "in_bytes": 1094834,
      "out_bytes": 0,
      "subscriptions": 0,
      "lang": "go",
      "version": "1.3.0"
    },
    {
      "cid": 3,
      "ip": "10.1.0.192",
      "port": 47332,
      "start": "2019-11-19T10:35:56.8050485Z",
      "last_activity": "2019-11-19T11:47:50.0024605Z",
      "rtt": "349µs",
      "uptime": "1h11m53s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 12062,
      "out_msgs": 0,
      "in_bytes": 3084386,
      "out_bytes": 0,
      "subscriptions": 0,
      "lang": "go",
      "version": "1.5.0"
    }
  ]

Now , What is I doing wrong? Maybe I need to launch a new spout as mode=Filter ? 

Thanks

**Comment by mjs** [comment]
influx-spout is intended to be used with a variety of instances of the influx-spout binary running in different configurations. They work together, passing data to each other via NATS subjects (see the diagram in README.md). 

Running a UDP listener by itself won't be all the useful, but that said you *should* be able to see the metrics sent by telegraf using influx-spout-tap.

Can you provide the influx-spout listener configuration that you're using? 

What output is influx-spout logging?

You could also try setting `debug = true` in the config and seeing if there's any useful there.

**Comment by mjs** [comment]
I just checked one deployment that I have access to and I'm pretty sure you want to use the telegraf's `[[outputs.influxdb]]` output (not `[[outputs.socket_writer]]`)

**Comment by jmorcar** [comment]
Ok I have to test it yet but makes sense using influxdb output plugin. I had'n notice that your influx-spout be able to read o influx protocol.

**Comment by mjs** [comment]
The project is being archived.
