### ISSUE TITLE
Add configuration option for InfluxDB writer over HTTPS

### ISSUE THREAD

**Issue by jortkoopmans** [jumptrading/influx-spout#145]
The current implementation of the InfluxDB Writer must use http transport.
It would be nice to also be able to use https, for cases where InfluxDB is configured to use/require that. This would be expected in scenario's where networks cannot be trusted.

Ideally;
- Non-breaking change (for all existing users).
- Simple optional configuration flag to enable https.

**Comment by jortkoopmans** [comment]
Anybody else interested in this feature or wanting to review it?
Perhaps @mjs , as you've recently also been supportive?

**Comment by paulcostinean** [comment]
cc @oplehto

**Comment by mjs** [comment]
This was done in #146.
