### ISSUE TITLE
Slow consumer test

### ISSUE THREAD

**Issue by mjs** [jumptrading/influx-spout#32]
The end-to-end testing suite should have a "slow consumer" test which can be used to replicate the scenarios which have been experienced in production use.

A slow consumer has in the past caused high memory consumption in the influx-spout writer. Although these issues have been fixed we should have a test to guard against regression.

**Comment by wrigtim** [comment]
Also noticed instances where a single slow-consumer appears to impact others (reproduced with a remote connection to NATS over a high-latency WAN link), i.e. the high-latency client was marked slow, but the metric rate dropped to other local subscribers.

Also while the NATS server only keeps a count of the slow consumers, the writer would know it was kicked and why. Should we add stats for the number of reconnections and the number of times it was labelled slow?

Ref https://github.com/nats-io/gnatsd/issues/296
