### ISSUE TITLE
SIGHUP support in writers & filters 

### ISSUE THREAD

**Issue by mjs** [jumptrading/influx-spout#36]
It would be nice if instead of hard-restarting the nodes, we could send them a SIGHUP to ask them to reload their configuration from the disk.

**Comment by oplehto** [comment]
Based on practical experience, restarting the components seems to be minimally disruptive. This is further mitigated in a container orchestration environment where the rolling restarts are pretty straightforward. 

OTOH ensuring that SIGTERM is handled gracefully is important and I think we are doing that part pretty well.

**Comment by SEJeff** [comment]
We don’t have livenessprobes, so a zero downtime rolling restart is currently impossible for listeners. Ideally, we would have a signal that tells spout to stop accepting new connections, finish servicing all in flight ones, and exit with a return code of zero.

In the kubernetes pod stop lifecycle, it will send a pod a term signal. Kubernetes native applications will trap the term and not exit until they’re finished with all outstanding requests. Then we use a rolling update to not drop messages inflight (with a few tweaks in the kubernetes deployment yaml).

[Here are the docs](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/). It is pretty flexible. As an example, nginx supports a `-s SIGNAL` flag so you can do `nginx -s QUIT` and a sigquit will cause nginx to gracefully shut down.

**Comment by mjs** [comment]
After talking with @oplehto , we don't think this is required now. The preferred approach is restart components rather than asking them to reload state (keeps internals simpler) and all the influx-spout components have liveness probes now.
