### ISSUE TITLE
Endpoints for Kubernetes liveness and readiness probes

### ISSUE THREAD

**Issue by oplehto** [jumptrading/influx-spout#53]
It would be very useful to have HTTP endpoints that are designed for [Kubernetes liveness and readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) on each of the influx-spout components.

**Comment by SEJeff** [comment]
Ideally it would be something like `/healthz`, which is what many golang apps are using and kubernetes has adopted.

readinessProbe: app is fully spun up and ready to service requests
livenessProbe: app is healthy

For web apps, I’ll generally make it do the equiv of `SELECT 1` for the livenessProbes. You can make them separate endpoints but it is generally accepted to just use the same endpoint for both.
