### ISSUE TITLE
HTTP listener: Support for the time resolution parameter 

### ISSUE THREAD

**Issue by oplehto** [jumptrading/influx-spout#72]
Right now influx-spout assumes that all the data is in nanoseconds, however it is possible to define this in the HTTP interface using the "resolution" query parameter: https://docs.influxdata.com/influxdb/v1.5/tools/api/#write

The HTTP listener should parse this parameter and convert the incoming measurements' time stamps to the nanosecond format accordingly.

**Comment by mjs** [comment]
@oplehto I presume you mean the `precision` parameter? I don't see a parameter named `resolution` in the docs.

**Comment by oplehto** [comment]
Yes, `precision` parameter of course. Sorry for the confusion
